defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

sweep:
  dir: ${experiment.log_dir}/hydra_outputs/

mode: MULTIRUN

sweeper:
  params:
    data: cancer
    model.num_of_hidden: 2 #3,4,5
    model.dim_of_hidden: 80,100 #40,80,100 #range(${model.dim_of_in},10) #,8)
    activation: tanh,prelu,relu,split_tanh,split_sincos #,split_sign,sigmoid
    experiment.seed: range(0,${experiment.n_experiments})
