experiment:
  wandb_project: TCExperiments
  n_experiments: 10

defaults:
  - data: circles
  - activation: relu
  - model: classifierAL
  - trainer: default
  - experiment: default
  - logging: default
  - hydra: default_multirun
  - _self_
